"use strict";

const citations = [
  {
    texte: "Si vous voulez vivre une vie heureuse, attachez-la à un but, et non pas à des personnes ou à des choses.",
    auteur: "Albert Einstein",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "En plein coeur de toute difficulté se cache une possibilité.",
    auteur: "Albert Einstein",
    categorie: ["courage", "sagesse"],
    image: [],
  },
  {
    texte: "La seule chose qui fait que la vie mérite d'être vécue, c'est de vivre pour les autres.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "morale", "sagesse"],
    image: [],
  },
  {
    texte: "Ce qui faît la vrai valeur d'un être humain, c'est de s'être délivré de son petit moi.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Je dois être prêt à renoncer à ce que je suis pour devenir ce que je serai.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "courage"],
    image: [],
  },
  {
    texte: "N'essayez pas de devenir un homme qui a du succès, essayez de devenir un homme qui a de la valeur.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Rare est le nombre de ceux qui regardent avec leurs propres yeux et qui éprouvent avec leur propre sensibilité.",
    auteur: "Albert Einstein",
    categorie: ["sensibilite"],
    image: [],
  },
  {
    texte: "Tout ce que est vraiment grand et inspiré a été réalisé par des individus travaillant librement.",
    auteur: "Albert Einstein",
    categorie: ["liberte"],
    image: [],
  },
  {
    texte: "Deux choses sont infinies: l'univers et la bêtise humaine. Mais en ce qui concerne l'univers, je n'ai pas de certitude absolue.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Il est plus facile de désintégrer un atome qu'un préjugé.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La logique vous mènera d'un point A à un point B. L'imagination vous emmènera partout.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",
    auteur: "Albert Einstein",
    categorie: ["courage"],
    image: [],
  },
  {
    texte: "Le mot progrès n'aura aucun sens tant qu'il y'aura des enfants malheureux.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "morale"],
    image: [],
  },
  {
    texte: "Le problème aujourd'hui n'est pas l'énergie atomique, mais le coeur des hommes.",
    auteur: "Albert Einstein",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Tout le monde est un génie. Mais si on juge un poisson sur sa capacité à grimper à un arbre, il passera sa vie à croire qu'il est stupide.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Une personne qui n'a jamais commis d'erreurs n'a jamais tenté d'innover.",
    auteur: "Albert Einstein",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Le monde ne sera pas détruit par ceux qui font le mal, mais par ceux qui les regardent sans rien faire.",
    auteur: "Albert Einstein",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Le sort de l'humanité en général sera celui qu'elle méritera.",
    auteur: "Albert Einstein",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "L'humanité se passionne pour des buts dérisoires. Ils s'appellent la richesse, la gloire, le luxe.",
    auteur: "Albert Einstein",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "Ce qui compte ne peut pas toujours être compté. Ce qui peut être compté ne compte pas forcément.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "sagesse"],
    image: [],
  },
  {
    texte: "Si la vue d'un bureau encombré évoque un esprit encombré, alors que penser d'un bureau vide ?",
    auteur: "Albert Einstein",
    categorie: [],
    image: [],
  },
  {
    texte: "Pour être un membre irréprochable d'une communauté de moutons, il faut avant tout être soi-même un mouton.",
    auteur: "Albert Einstein",
    categorie: ["liberte"],
    image: [],
  },
  {
    texte: "Inventer, c'est penser à côté.",
    auteur: "Albert Einstein",
    categorie: ["liberte"],
    image: [],
  },
  {
    texte: "Les grands esprits ont toujours dû affronter une opposition violente de la part des esprits médiocres.",
    auteur: "Albert Einstein",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Ne fais jamais rien contre ta conscience, même si l'Etat te le demande.",
    auteur: "Albert Einstein",
    categorie: ["liberte", "morale"],
    image: [],
  },
  {
    texte: "La liberté consiste à se discipliner au lieu de se laisser discipliner.",
    auteur: "Albert Einstein",
    categorie: ["liberte", "sagesse"],
    image: [],
  },
  {
    texte: "C'est la personne humaine, libre, créatrice et sensible qui façonne le beau et le sublime, alors que les masses restent entraînées dans une ronde infernale d'imbécillité et d'abrutissement.",
    auteur: "Albert Einstein",
    categorie: ["liberte", "courage"],
    image: [],
  },
  {
    texte: "La joie de regarder et de comprendre est le plus beau cadeau de la nature.",
    auteur: "Albert Einstein",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "Il n'y a pas d'échec, il n'y que des abandons.",
    auteur: "Albert Einstein",
    categorie: ["courage"],
    image: [],
  },
  {
    texte: "C'est le devoir de chaque homme de rendre au moins autant qu'il en a reçu.",
    auteur: "Albert Einstein",
    categorie: [],
    image: [],
  },
  {
    texte: "Les médias sont l’entité la plus puissante sur terre. Ils ont le pouvoir de faire les innocents coupables et rendre coupable l’innocent, et ça c’est pouvoir. Parce qu’ils contrôlent l’esprit des masses.",
    auteur: "Malcom X",
    categorie: ["liberte", "morale"],
    image: [],
  },
  {
    texte: "Si vous n'êtes pas vigilants, les médias arriveront à vous faire détester les gens opprimés et aimer ceux qui les oppriment.",
    auteur: "Malcolm X",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Si vous ne vous levez pas pour quelque chose. Vous tomberez pour n'importe quoi.",
    auteur: "Malcolm X",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Si vous n'êtes pas prêt à mourir pour elle, sortez le mot \"liberté\" de votre vocabulaire.",
    auteur: "Malcolm X",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Quand vous commencez à penser par vous-mêmes, vous leur faites peur, et ils s'efforcent de vous interdire tout contact avec l'opinion publique, de peur que si l'opinion publique vous écoute, elle ne veuille plus les écouter.",
    auteur: "Malcolm X",
    categorie: ["courage", "liberte"],
    image: [],
  },
];
