"use strict";

const citations = [
  {
    texte: "Si vous voulez vivre une vie heureuse, attachez-la à un but, et non pas à des personnes ou à des choses.",
    auteur: "Albert Einstein",
    categorie: ["bonheur"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "En plein coeur de toute difficulté se cache une possibilité.",
    auteur: "Albert Einstein",
    categorie: ["courage", "sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "La seule chose qui fait que la vie mérite d'être vécue, c'est de vivre pour les autres.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "morale", "sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Ce qui faît la vrai valeur d'un être humain, c'est de s'être délivré de son petit moi.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Je dois être prêt à renoncer à ce que je suis pour devenir ce que je serai.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "courage"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "N'essayez pas de devenir un homme qui a du succès, essayez de devenir un homme qui a de la valeur.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Rare est le nombre de ceux qui regardent avec leurs propres yeux et qui éprouvent avec leur propre sensibilité.",
    auteur: "Albert Einstein",
    categorie: ["sensibilite"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Tout ce que est vraiment grand et inspiré a été réalisé par des individus travaillant librement.",
    auteur: "Albert Einstein",
    categorie: ["liberte"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Deux choses sont infinies: l'univers et la bêtise humaine. Mais en ce qui concerne l'univers, je n'ai pas de certitude absolue.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Il est plus facile de désintégrer un atome qu'un préjugé.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "La logique vous mènera d'un point A à un point B. L'imagination vous emmènera partout.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "La vie, c'est comme une bicyclette, il faut avancer pour ne pas perdre l'équilibre.",
    auteur: "Albert Einstein",
    categorie: ["courage"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Le mot progrès n'aura aucun sens tant qu'il y'aura des enfants malheureux.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "morale"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Le problème aujourd'hui n'est pas l'énergie atomique, mais le coeur des hommes.",
    auteur: "Albert Einstein",
    categorie: ["morale"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Tout le monde est un génie. Mais si on juge un poisson sur sa capacité à grimper à un arbre, il passera sa vie à croire qu'il est stupide.",
    auteur: "Albert Einstein",
    categorie: ["sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Une personne qui n'a jamais commis d'erreurs n'a jamais tenté d'innover.",
    auteur: "Albert Einstein",
    categorie: ["courage", "liberte"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Le monde ne sera pas détruit par ceux qui font le mal, mais par ceux qui les regardent sans rien faire.",
    auteur: "Albert Einstein",
    categorie: ["morale"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Le sort de l'humanité en général sera celui qu'elle méritera.",
    auteur: "Albert Einstein",
    categorie: ["morale"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "L'humanité se passionne pour des buts dérisoires. Ils s'appellent la richesse, la gloire, le luxe.",
    auteur: "Albert Einstein",
    categorie: ["bonheur"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Ce qui compte ne peut pas toujours être compté. Ce qui peut être compté ne compte pas forcément.",
    auteur: "Albert Einstein",
    categorie: ["bonheur", "sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Si la vue d'un bureau encombré évoque un esprit encombré, alors que penser d'un bureau vide ?",
    auteur: "Albert Einstein",
    categorie: [],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Pour être un membre irréprochable d'une communauté de moutons, il faut avant tout être soi-même un mouton.",
    auteur: "Albert Einstein",
    categorie: ["liberte"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Inventer, c'est penser à côté.",
    auteur: "Albert Einstein",
    categorie: ["liberte"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Les grands esprits ont toujours dû affronter une opposition violente de la part des esprits médiocres.",
    auteur: "Albert Einstein",
    categorie: ["courage", "liberte"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Ne fais jamais rien contre ta conscience, même si l'Etat te le demande.",
    auteur: "Albert Einstein",
    categorie: ["liberte", "morale"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "La liberté consiste à se discipliner au lieu de se laisser discipliner.",
    auteur: "Albert Einstein",
    categorie: ["liberte", "sagesse"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "C'est la personne humaine, libre, créatrice et sensible qui façonne le beau et le sublime, alors que les masses restent entraînées dans une ronde infernale d'imbécillité et d'abrutissement.",
    auteur: "Albert Einstein",
    categorie: ["liberte", "courage"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "La joie de regarder et de comprendre est le plus beau cadeau de la nature.",
    auteur: "Albert Einstein",
    categorie: ["bonheur"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Il n'y a pas d'échec, il n'y que des abandons.",
    auteur: "Albert Einstein",
    categorie: ["courage"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "C'est le devoir de chaque homme de rendre au moins autant qu'il en a reçu.",
    auteur: "Albert Einstein",
    categorie: [],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Les médias sont l’entité la plus puissante sur terre. Ils ont le pouvoir de faire les innocents coupables et rendre coupable l’innocent, et ça c’est pouvoir. Parce qu’ils contrôlent l’esprit des masses.",
    auteur: "Malcom X",
    categorie: ["liberte", "morale"],
    image: ["Albert_Einstein.jpg"],
  },
  {
    texte: "Si vous n'êtes pas vigilants, les médias arriveront à vous faire détester les gens opprimés et aimer ceux qui les oppriment.",
    auteur: "Malcolm X",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Si vous ne vous levez pas pour quelque chose. Vous tomberez pour n'importe quoi.",
    auteur: "Malcolm X",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Si vous n'êtes pas prêt à mourir pour elle, sortez le mot \"liberté\" de votre vocabulaire.",
    auteur: "Malcolm X",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Quand vous commencez à penser par vous-mêmes, vous leur faites peur, et ils s'efforcent de vous interdire tout contact avec l'opinion publique, de peur que si l'opinion publique vous écoute, elle ne veuille plus les écouter.",
    auteur: "Malcolm X",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Il y'a souvent plus de choses naufragées au fond d'une âme qu'au fond de la mer.",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "Mieux vaut une conscience tranquille qu'une destinée prospère. J'aime mieux un bon sommeil qu'un bon lit.",
    auteur: "Victor Hugo",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La haine, c'est l'hiver qui s'empare du coeur.",
    auteur: "Victor Hugo",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "Vous voulez la misère secourue. Moi je la veux supprimée.",
    auteur: "Victor Hugo",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Quand je suis triste, je pense à vous, comme l'hiver on pense au soleil, et quand je suis gai, je pense à vous, comme en plein soleil on pense à l'ombre.",
    auteur: "Victor Hugo",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "Les larmes sont un don. Souvent les pleurs, après l'erreur ou l'abandon, raniment nos forces brisées.",
    auteur: "Victor Hugo",
    categorie: ["bonheur", "courage"],
    image: [],
  },
  {
    texte: "Le plus grand ennui, c'est d'exister sans vivre.",
    auteur: "Victor Hugo",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "J'ai dans l'âme une fleur que nul ne peut cueillir.",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "Ceux qui vivent sont ceux qui luttent.",
    auteur: "Victor Hugo",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Mes amis, retenez ceci, il n'ya ni mauvaises herbes ni mauvais hommes. Il n'a que des mauvais cultivateurs.",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "Ouvrez des écoles, vous fermerez des prisons.",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "N'être pas écouté, ce n'est pas une raison pour se taire.",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "La liberté commence où l'ignorance finit.",
    auteur: "Victor Hugo",
    categorie: ["liberte", "sagesse"],
    image: [],
  },
  {
    texte: "La vérité est comme le soleil. Elle fait tout voir et ne se laisse pas regarder",
    auteur: "Victor Hugo",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "N'imitez rien ni personne. Un lion qui copie un lion devient un singe",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "La pensée et plus qu'un droite, c'est le souffle même de l'homme.",
    auteur: "Victor Hugo",
    categorie: ["liberte"],
    image: [],
  },
  {
    texte: "Quand une femme vous parle, écoutez ce qu'elle vous dit avec ses yeux.",
    auteur: "Victor Hugo",
    categorie: [],
    image: [],
  },
  {
    texte: "Il n'avait pas de gîte, pas de pain, pas de feu, pas d'amour; mais il était joyeux parce qu'il était libre.",
    auteur: "Victor Hugo",
    categorie: ["bonheur", "liberte"],
    image: [],
  },
  {
    texte: "Tu es blanche et je suis noir; mais le jour a besoin de s'unir à la nuit pour enfanter l'aurore et le couchant, qui sont plus beaux que lui !",
    auteur: "Victor Hugo",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Ce qui compte, chez un homme ce n'est pas la couleur de sa peau ou la texture de ses cheveux, mais la texte et la qualité de son âme.",
    auteur: "Martin Luther King",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "L'homme bon ne regarde pas les particularités physiques mais sait discerner ces qualités profondes qui rendent les gens humains, et donc frères.",
    auteur: "Martin Luther King",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Apprenons à vivre ensemble comme des frères ou nous mourrons tous ensemble comme des idiots.",
    auteur: "Martin Luther King",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Chaque fois que des hommes redressent l'échine, ils peuvent aller où ils veulent, car personne ne peut monter sur votre dos tant que vous vous tenez droit.",
    auteur: "Martin Luther King",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Croyez en vous rêves et ils se réaliseront peut-être. Croyez en vous et ils se réaliseront sûrement.",
    auteur: "Martin Luther King",
    categorie: ["bonheur", "courage"],
    image: [],
  },
  {
    texte: "L'obscurité ne peut pas chasser l'obscurité; seule la lumière le peut. La haine ne peut pas chasserla haine; seul l'amour le peut.",
    auteur: "Martin Luther King",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La non-violence est une arme puissante et juste, qui tranche sans blesser et ennoblit l'homme qui la manie.",
    auteur: "Martin Luther King",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "La question la plus persistante et la plus urgente de la vie est: \"que faites-vous pour les autres ?\"",
    auteur: "Martin Luther King",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Si tu ne peux pas voler, alors cours. Si tu ne peux pas courir, alors marche. Si tu ne peux pas marcher, alors rampe, mais quoi que tu fasses, tu dois continuer à avancer.",
    auteur: "Martin Luther King",
    categorie: ["courage"],
    image: [],
  },
  {
    texte: "Vivez les rêves que la vie vous défie de rêver.",
    auteur: "Martin Luther King",
    categorie: ["bonheur", "courage"],
    image: [],
  },
  {
    texte: "La véritable grandeur d'un homme ne se mesure pas à des moments où il est à son aise, mais lorqu'il traverse une pèriode de controverses et de défis.",
    auteur: "Martin Luther King",
    categorie: ["courage"],
    image: [],
  },
  {
    texte: "Chacun à la responsabilité morale de désobéir aux lois injustes.",
    auteur: "Martin Luther King",
    categorie: ["courage", "liberte", "morale"],
    image: [],
  },
  {
    texte: "Ce qui  m'effraie, ce n'est pas l'oppression des méchants; c'est l'indifférence des bons.",
    auteur: "Martin Luther King",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Nous vavons appris à voler dans les airs comme des oiseaux, nous avons appris à nager dans les océans comme des poissons, mais nous n'avons pas appris sur la terre à marcher comme des frères et soeurs.",
    auteur: "Martin Luther King",
    categorie: ["sagesse", "morale"],
    image: [],
  },
  {
    texte: "Ceux qui aiment la paix doivent apprendre à s'organiser aussi bien que ceux qui veulent la guerre.",
    auteur: "Martin Luther King",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La liberté n'est jamais volontairement donnée par l'oppresseur; elle doit être exigée par l'opprimé.",
    auteur: "Martin Luther King",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Une injustice, où qu'elle se produise, est une menace pour la justice partout ailleurs.",
    auteur: "Martin Luther King",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "A la fin, nous nous souviendrons non pas des mots de nos ennemis, mais des silences de nos amis.",
    auteur: "Martin Luther King",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Celui qui accepte le mal sans lutter contre lui coopère avec lui.",
    auteur: "Martin Luther King",
    categorie: ["courage", "morale"],
    image: [],
  },
  {
    texte: "Je fais le rêve qu'un jour mes enfants vivront dans une nation où ils ne seront pas jugés pour la couleur de leur peau, mais pour leur caractère.",
    auteur: "Martin Luther King",
    categorie: ["morale"],
    image: [],
  },
  {
    texte: "Vous pouvez avec certitude amèliorer un seul petit coin de l'univers: vous-même.",
    auteur: "Aldous Huxley",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La révolution véritablement révolutionnaire se réalisera, non pas dans le monde extérieur, mais dans l'âme et la chair des êtres humains.",
    auteur: "Aldous Huxley",
    categorie: ["liberte"],
    image: [],
  },
  {
    texte: "Comme si l'on croyait quoi que ce soit d'instinct ! On croit les choses parce qu'on a été conditionné à les croire.",
    auteur: "Aldous Huxley",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La victime de la manipulation mentale ignore qu'elle est une victime. Les murs de sa prison lui sont invisibles et elle se croit libre.",
    auteur: "Aldous Huxley",
    categorie: ["liberte"],
    image: [],
  },
  {
    texte: "La philosophie nous enseigne à douter de ce qui nous paraît évident. La progagande, au contraire, nous enseigne à accepter pour évident ce dont il serait raisonnable de douter.",
    auteur: "Aldous Huxley",
    categorie: ["liberte", "sagesse"],
    image: [],
  },
  {
    texte: "La plus grande partie de l'ignorance peut être vaincue. Nous ne savons pas, parce que nous ne voulons pas savoir.",
    auteur: "Aldous Huxley",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "La liberté ne s'accorde pas, elle s'arrache.",
    auteur: "Aldous Huxley",
    categorie: ["courage", "liberte"],
    image: [],
  },
  {
    texte: "Si l'on est différent, il est fatal qu'on soit seul.",
    auteur: "Aldous Huxley",
    categorie: ["sagesse"],
    image: [],
  },
  {
    texte: "Ne remettez jamais à demain le plaisir que vous pouvez prendre aujourd'hui.",
    auteur: "Aldous Huxley",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "On doit jouir de chaque moment, d'une manière passionnée, audacieuse, exaltante, unique.",
    auteur: "Aldous Huxley",
    categorie: ["bonheur"],
    image: [],
  },
  {
    texte: "Les conséquences de nos actions sont des épouvantails pour les lâches, et des rayons de lumière pour les sages.",
    auteur: "Aldous Huxley",
    categorie: ["courage", "sagesse"],
    image: [],
  },
  // {
  //   texte: ".",
  //   auteur: "Aldous Huxley",
  //   categorie: [],
  //   image: [],
  // },
  // {
  //   texte: ".",
  //   auteur: "Aldous Huxley",
  //   categorie: [],
  //   image: [],
  // },
  // {
  //   texte: ".",
  //   auteur: "Aldous Huxley",
  //   categorie: [],
  //   image: [],
  // },
  // {
  //   texte: ".",
  //   auteur: "Aldous Huxley",
  //   categorie: [],
  //   image: [],
  // },
  // {
  //   texte: ".",
  //   auteur: "Aldous Huxley",
  //   categorie: [],
  //   image: [],
  // },
];
